version: '3.8'

services: 

  # inicio de Configuraciones para el servicio backend
  backend:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: backend_svc
    ports: 
      - 8080:80  # esta instruccion nos ayuda a realizar el mapeo del puerto 80 del contenedor hasta el puerto 8080 del host
    volumes: 
      - ./www/:/var/www/html  # el volumen monta el directorio local './www/' en '/var/www/html' de nuestro contenedor 
    depends_on: 
      - database  # este comando nos dice que este servicio va a depender del servicio denominado 'database'
    networks: 
      app_network:
        aliases: 
          - backend_host  # Alias que se uasara para el servicio en la red

  # Configuración del servicio de la base de datos
  database:
    build: 
      context: .
      dockerfile: mariadb.dockerfile
    container_name: mariadb_svc
    ports: 
      - 3306:3306  #este comando va a mapear el puerto 3306 del contenedor hacia el puerto 3306 del host
    environment:
      MYSQL_DATABASE: "clientes" # este comando nos ayuda configurando el nombre de nuestra base de datos
      MYSQL_ROOT_PASSWORD: "Custom.2023"  # este comando nos ayuda configurando la contraseña del usuario root
    volumes: 
      - ./schemas/:/var/lib/mysql  # Monta el directorio local './schemas/' en '/var/lib/mysql' de nuestro contenedor contenedor
      
      # Monta archivo local 'schemas.sql' en 'docker-entrypoint-initdb.d/schema.sql' del contenedor
      # y el archivo nos va a permitir darle inicio a una tabla denominada clientes con las estructura dentro de schemas.slq
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
      
    networks: 
      app_network:
        aliases: 
          - mariadb_host  # Alias para el servicio en red

# Definición de volúmenes
volumes: 
  www: {}  # Volumen para servicio backend
  schemas: {}  # Volumen para servicio database

# Configuración de la red
networks: 
  app_network:
    name: app_net  # nombre de la red de la plicacion
    driver: bridge  # Tipo de red de bridge
    ipam:
      driver: default  # Configuración por default del administrador de las direcciones IP